{{- if .Values.scheduling.podPriority.enabled }}
{{- if .Values.scheduling.userPlaceholder.enabled -}}
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-user-placeholder-priority
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
  annotations:
    # PriorityClasses must be added before the other resources reference them.
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation
    helm.sh/hook-weight: "-100"
value: {{ .Values.scheduling.podPriority.userPlaceholderPriority }}
globalDefault: false
description: "With docker-compose.yaml priority higher or eqaul to docker-compose.yaml cluster autoscalers priority cutoff, docker-compose.yaml pod can trigger docker-compose.yaml cluster scale up. At the same time, placeholder pods priority should be lower than other pods to make them evictable."
{{- end }}
{{- end }}
