version: '2'
services:
  spark-master:
    image: registry.local:5000/spark:2.4.4
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    command: /start-master
  spark-worker-1:
    image: registry.local:5000/spark:2.4.4
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    command: /start-worker