version: '3'
services:

#############################################
#               ZEPPELIN                    #
#############################################
  zeppelin-standalone:
    image: apache/zeppelin:0.9.0
    ports:
      - "8180:8080"
      - "4140:4040"
    volumes:
      - "../../../_volume/zeppelin/notebook:/zeppelin/notebook"
      - "../../../_volume/zeppelin/data:/zeppelin/data"

