version: '3'
services:

#############################################
#               ZEPPELIN                    #
#############################################
  zeppelin-standalone:
    image: apache/zeppelin:0.9.0

    environment:
      ZEPPELIN_PORT: 8080
      ZEPPELIN_INTP_MEM:
        -Xms1024m
        -Xmx4g
        -XX:MaxPermSize=4g
      ZEPPELIN_JAVA_OPTS:
        -Dspark.driver.memory=2g
        -Dspark.executor.memory=4g
        -Dspark.cores.max=2
      MASTER: local[*]

    ports:
      - "8180:8080"
      - "4140:4040"
    volumes:
      - "../../../_volume/zeppelin/notebook:/zeppelin/notebook"
      - "../../../_volume/zeppelin/data:/zeppelin/data"
      - "../../../_volume/zeppelin/log:/zeppelin/log"

