version: '3'
services:
  docker-registry:
    image: registry:2
    container_name: registry-local
    hostname: registry.local
    ports:
      - "5000:5000"
    volumes:
      - "../../../_volume/docker_registry:/var/lib/registry"
    restart: always
    networks:
      - ginger-network
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
  docker-registry-ui:
    image: parabuzzle/craneoperator:latest
    container_name: docker-registry-ui
    ports:
      - "8086:80"
    environment:
      - REGISTRY_HOST=registry.local
      - REGISTRY_PORT=5000
      - REGISTRY_PROTOCOL=http
      - SSL_VERIFY=false
      - USERNAME=admin
      - PASSWORD=mypassword
      - REGISTRY_ALLOW_DELETE=true
    restart: always
    networks:
      - ginger-network
    depends_on:
      - docker-registry

networks:
  ginger-network: {
    name: ginger-network
  }
