kind: Service
apiVersion: v1
metadata:
  name: spark-master-headless
spec:
  ports:
  clusterIP: None
  selector:
    app: spark-master
---
kind: Service
apiVersion: v1
metadata:
  name: spark-master
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
    - name: spark
      nodePort: 31077
      port: 7077
      targetPort: 7077
      protocol: TCP
    - name: http
      nodePort: 31080
      port: 8080
      targetPort: 8080
    - name: job-1
      nodePort: 31040
      port: 4040
      targetPort: 4040