kind: Service
apiVersion: v1
metadata:
  name: zeppelin-server
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: zeppelin-server
  ports:
    - name: http
      nodePort: 31081
      port: 80
      targetPort: 8080
    - name: rpc            # port name is referenced in the code. So it shouldn't be changed.
      port: 12320
      targetPort: 12320

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zeppelin-server
