kind: Service
apiVersion: v1
metadata:
  name: zeppelin
spec:
  type: NodePort
  selector:
    app: zeppelin
  ports:
    - name: ui
      nodePort: 31081
      port: 80
      targetPort: 8081
    - name: rpc            # port name is referenced in the code. So it shouldn't be changed.
      port: 12320
      targetPort: 12320

#---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: zeppelin
#---
#
#---
#kind: Role
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: zeppelin-server-role
#rules:
#  - apiGroups: [""]
#    resources: ["pods", "services"]
#    verbs: ["create", "get", "update", "patch", "list", "delete", "watch"]
#  - apiGroups: ["rbac.authorization.k8s.io"]
#    resources: ["roles", "rolebindings"]
#    verbs: ["bind", "create", "get", "update", "patch", "list", "delete", "watch"]
#---
#
#---
#kind: RoleBinding
#apiVersion: rbac.authorization.k8s.io/v1
#metadata:
#  name: zeppelin-server-role-binding
#subjects:
#  - kind: ServiceAccount
#    name: zeppelin
#roleRef:
#  kind: Role
#  name: zeppelin-server-role
#  apiGroup: rbac.authorization.k8s.io
#---
